### ISSUE TITLE
No ionio accounts found error

### ISSUE THREAD

**Issue by stefanopepe** [vulpemventures/marina#534]
Pressing "Download" button in Settings/Accounts fails with a "no Ionio accounts found" error.
Expected behavior is download wallet descriptors and/or xpub data to set up a watch-only wallet somewhere else.

App v3-0.6.4
Chrome 125.0.6422.142 Arm64
MacOS 13.6.5

Console log:
```
index.js:2 Error: no Ionio accounts found
    at m (index.js:2:3948707)
    at onClick (index.js:2:3950909)
    at onClick (index.js:2:3857249)
    at Object.He (index.js:2:3581807)
    at Ye (index.js:2:3581961)
    at index.js:2:3601843
    at Ln (index.js:2:3601937)
    at Fn (index.js:2:3602351)
    at index.js:2:3607789
    at uc (index.js:2:3671160)
    at xe (index.js:2:3580940)
    at jn (index.js:2:3603643)
    at zt (index.js:2:3588054)
    at qt (index.js:2:3587838)
    at HTMLDivElement.n (index.js:2:86360)
(anonymous) @ index.js:2
```

Thank you for your great work so far! Happy to provide additional info and/or try to reproduce the error starting from scratch.

**Comment by stefanopepe** [comment]
<img width="370" alt="Screenshot 2024-06-16 at 20 02 35" src="https://github.com/vulpemventures/marina/assets/6222429/ed5a7de7-f7a5-4079-b56c-081136eae790">

**Comment by tiero** [comment]
I think this is expected as that features is for when you create custom script accounts. It doesn't seem the case right?

**Comment by stefanopepe** [comment]
yes, correct, the wallet is “vanilla” with no custom accounts.
